CC = g++
CFLAGS = -g -Wall -Wextra --std=c++20

SRCS = src/ComparablePointer.cpp src/model.cpp src/strategy.cpp src/OrderBook.cpp src/Order.cpp src/indicator.cpp src/witchpot.cpp src/Timestamp.cpp src/FeedEntry.cpp src/Timeseries.cpp
OBJS = obj/ComparablePointer.o   obj/model.o   obj/strategy.o   obj/OrderBook.o   obj/Order.o   obj/indicator.o   obj/witchpot.o   obj/Timestamp.o   obj/FeedEntry.o   obj/Timeseries.o
EXEC = bin/witchbot

.PHONY: all clean

all: $(EXEC)

$(EXEC): $(OBJS)
	$(CC) $(LDFLAGS) $(OBJS) -o $@

obj/%.o: src/%.cpp
	$(CC) $(CFLAGS) -c $< -o $@

clean:
	rm -rf obj/*.o $(EXEC)

# leaks --atExit -- bin/witchbot 